### ISSUE TITLE
Create JoinProject.md

### ISSUE THREAD

**Issue by Geson-anko** [Geson-anko/JarvisEngine#159]
Please create `JoinProject.md`. This is a **markdown** file written how to join JarvisEngine Project.
Please describe the steps you took to successfully run `python -m JarvisEngine run -d TestEngineProject` from the pure OS state.
Written Language is **English**.

### Steps
1. Please `fork` this repository to your account.
2. `git clone` it onto your PC.
3. `checkout` ( switch branch) to `dev` by running a command `git checkout dev`
4.  Switch to a branch named `feature/JoinProject.md` and create `JoinProject.md`.
5. Send *pull request* named `Create JoinProject.md` to this project `dev` branch.
6. Please write a simple message to *pull request*
7. After some modifications, merge and you are done.

### Validation
- After `JoinProject.md`, `python -m JarvisEngine run -d TestEngineProject` should complete successfully
- The procedure should be easy to understand.
- The procedure should be easy to understand.
- Must be in English

### limit
5/26

---------------
# 日本語
`JoinProject.md`を作成します。JarvisEngineを開発可能な状態にするための方法を記述したファイルです。
通常のOSの状態から、`python -m JarvisEngine run -d TestEngineProject`を正常に実行できるまでの手順を記してください。
英語で記述してください。
### 手順
1. このリポジトリを`fork`してください。
9. `fork` 先の自分のリポジトリをPCに`git clone`してください。
10. `git checkout dev`で`dev`ブランチにswitchしてください
11. `feature/JoinProject.md`という名前でブランチを切り替え、`JoinProject.md`を作成してください。
12.  私の`dev`ブランチに、`Create JoinProject.md`という名前でpull requestを送信してください。
13. pull requestに簡潔なメッセージを書いてください。
14. いくつかの修正の後、マージしたら完了です。

### 評価
- `JoinProject.md`の後、`python -m JarvisEngine run -d TestEngineProject`が正常に完了すること
- 手順がわかりやすいこと
- markdownで書かれていること
- 英語であること

### 期限
5/26

**Comment by 2718proton** [comment]
# Jarvis Engine
Jarvis engine is an AI Engine for complex processing, parallel processing, and even linking with game engines.

## How to join us
To join us at Jarvis engine, please follow the steps below.
1. Please 'fork' this repository to your account.
2. Please 'git clone' the repository onto your pc.
```bash
git clone https://github.com/Geson-anko/JarvisEngine.git
```
3. Run 'git checkout dev' to switch branch
```bash
git checkout dev
```
4. Switch to a branch named 'feature/JoinProject.md' and create 'JoinProject.md'.
```bash
cd JarvisEngine
```
5. Please send *pull request* named 'Create JoinProject.md' to this project 'dev' branch. (Write a simple message to *pull request*)
6. And you are done.

## Validation
By running 'TestEngineProject', You can confirm complete installation of Jarvis Engine.
```bash
python -m JarvisEngine run -d TestEngineProject
```

## Caution
To run Jarvis Engine, it is required to install 'poetry'.
